build: Remove release option when running tests
Running the tests with `--release` causes the following error:

```sh
$ make check
cargo test --target x86_64-unknown-linux-musl --release
    Finished release [optimized] target(s) in 0.03s
     Running target/x86_64-unknown-linux-musl/release/deps/kata_agent-f0880e5dfeba484a
error: could not execute process `/home/james/git/rust/kata-rust-agent/target/x86_64-unknown-linux-musl/release/deps/kata_agent-f0880e5dfeba484a` (never executed)

Caused by:
  No such file or directory (os error 2)
make: *** [Makefile:63: check] Error 101
```

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>